---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: app
type: Opaque
stringData:
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_USER: myapp
  DB_PASSWORD: myapp123
  DB_NAME: myapp
  REDIS_HOST: redis
  REDIS_PORT: "6379"